config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'users#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[show] do
        resources :posts, only: %i[index] do
          resources :comments, only: %i[create index]
        end
      end
    end
  end

  resources :users, only: [] do
    member do
      get 'apitoken'
    end
  end

  resources :users, only: %i[show index] do
    resources :posts, only: %i[show index create new destroy]
  end

  resources :posts do
      resources :comments, only: %i[create new update destroy]
      resources :likes, only: %i[create] 
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :read, :all
    if user.admin? :admin
      can :manage, :all
    else
      can :manage, Comment, user_id: user.id
      can :manage, Post, user_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_comments
    Comment.last(5)
  end

  def update_posts_counter
    user.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'user_id'
  has_many :comments, foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :generate_api_token

  def admin?(requested_role)
    role == requested_role.to_s
  end

  def recent_posts
    Post.last(3)
  end

  def generate_api_token
    self.apitoken = Devise.friendly_token
    save
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    render json: @comments, status: :ok
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    if @comment.save
      render json: { status: 201, message: 'Comment creation success!', content: { comment: @comment } }
    else
      render json: @comment.errors, status: :bad_request, message: 'Failed!'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    render json: @posts, status: :ok
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    render json: @user, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_with_token
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :posts_counter, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def authenticate_with_token
    return unless params[:apitoken]

    user = User.find_by_api_token(params[:apitoken])
    sign_in(user)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @new_comment = current_user.comments.new(
      text: comment_params,
      user_id: current_user.id,
      post_id: @post.id
    )
    @new_comment.post_id = @post.id
    @new_comment.update_comments_counter
    if @new_comment.save
      redirect_to "/users/#{@post.user_id}/posts/#{@post.id}", flash: { alert: 'Comment created' }
    else
      flash.now[:error] = 'An error ocurred, could not save comment'
      render action: 'new'
    end
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    post = Post.find_by(id: @comment.post_id)
    post.comments_counter -= 1
    @comment.destroy!
    flash[:success] = 'Comment deleted'
    redirect_to user_post_path(current_user.id, post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)[:text]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    new_like = current_user.likes.new(
      user_id: current_user.id,
      post_id: @post.id
    )
    new_like.update_likes_counter
    if new_like.save
      redirect_to "/users/#{@post.user_id}/posts/#{@post.id}", flash: { alert: 'Liked!' }
    else
      redirect_to "/users/#{@post.user_id}/posts/#{@post.id}",
                  flash.now[:error] = 'An error occured, like could not be saved'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments
    @likes = @post.likes
  end

  def new
    @post = Post.new
  end

  def create
    @new_post = current_user.posts.new(post_params)
    @new_post.likes_counter = 0
    @new_post.comments_counter = 0
    @new_post.update_posts_counter
    respond_to do |format|
      format.html do
        if @new_post.save
          redirect_to "/users/#{@new_post.user.id}/posts/", flash: { alert: 'Success! Post Created' }
        else
          render :new, flash.now[:error] = 'An error ocurred, post could not be saved'
          render action: 'new'
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    user = User.find(params[:user_id])
    user.posts_counter -= 1
    @post.destroy!
    user.save
    flash[:success] = 'Post deleted'
    redirect_to user_posts_path(user.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def apitoken
    @user = User.find(params[:id])
    render json: @user.apitoken, status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CicloBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel= "stylesheet" href = "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'devise/shared/navbar' %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_create_comments.html.erb
<%= form_with url: "/posts/#{@post.id}/comments", scope: :comment do |form| %>
    <div>
        <%= form.text_area :text, placeholder: 'Enter your comment', rows: 15, required: true %>
        <%= form.submit 'Submit comment', class: 'submit-btn' %>
    </div>
<% end %>

app/views/posts/index.html.erb
<div class='all-posts-body'>
    <div class='u-detail-top'>
        <div class='u-d-img'>
            <%= image_tag 'image-placeholder.png', width: '150px', height: '150px' %>
        </div>

        <div class='u-detail-user'>
            <h1 class='u-detail-user-name'>
                <%= @user.name  %>
            </h1>
            <p class='u-detail-user-counter'>
                Number of posts: <%= @user.posts_counter %>
            </p>
        </div>
    </div>

    <div class='create-post-cont'>
        <%= link_to "Create new post", new_user_post_path %>
    </div>

    <div class='u-detail-rec-posts'>
        <% @posts.each  do |post| %>
            <div class='u-detail-rec-posts-card'>
                <h2>
                    <%= link_to "#{post.title}", user_post_path(@user.id, post.id), class: 'post-link' %>
                </h2>
                <p>
                    <%= post.text %>
                </p>

                <% if can? :destroy, post %>
                    <%= button_to "Delete Post", user_post_path(@user.id, post.id), :method => :delete, class: 'del' %>
                <% end %>
 
                <div class='com-lik-counters'>
                    <p>Comments: <%= post.comments_counter %></p>
                    <p>Likes: <%= post.likes_counter %></p>
                </div>
            </div>

            <div class='post-comments'>
                <% post.recent_comments.each do |comment| %>
                    <h3>
                        <%= comment.user.name %>: <%= comment.text  %>
                    </h3>
                <% end %>
            </div>
        <% end %>

        <button class='pagination-btn'>
            Pagination
        </button>
    </div>
</div>

app/views/posts/new.html.erb
<div class='post-form'>
    <h2 class='post-form-title'>Create new post</h2>

    <%= form_with model: @post, url: user_posts_path, scope: :post  do |form| %>
        <div class='post-form-title-field'>
            <%= form.text_field :title, placeholder: 'Enter post title', required: true %>
        </div>

        <div class='post-form-text-field'>
            <%= form.text_area :text, placeholder: 'Enter post content', rows: 20, required: true %>
        </div>

        <%= form.submit 'Submit post', class: 'post-submit-btn'  %>
    <%end%>
</div>

app/views/posts/show.html.erb
<div class='post-details-body'>
    <div class='post-details-p-card'>
        <div class='post-details-top'>
            <h3>
                <%= @post.title %> by <%= @post.user.name %>
            </h3>

            <div class='post-com-lik-counters'>
                <p>
                    Comments: <%= @post.comments_counter%>
                </p>
                <p>
                    Likes: <%= @post.likes_counter%>
                </p>
            </div>
        </div>
        
        <%= form_with url: "/posts/#{@post.id}/likes", scope: :like do |form| %>
            <%= form.submit "Like this post", class: "post-like-btn"%>
        <% end %>

        <p class='post-details-text'>
            <%= @post.text %>
        </p>
    </div>

    <div class='post-details-p-comments'>
        <% @comments.each do |comment| %>
            <p>
                <%= comment.user.name%>: <%= comment.text%>
            </p>
            <% if can? :destroy, comment %>
                <%= button_to "Delete Comment", "/posts/:post_id/comments/#{params[:id]}", method: :delete, params: { comment_id: comment.id }, class: 'del' %>
            <% end %>

        <% end %>
    </div>

    <div class = 'comment-creator'>
        <%= render "posts/create_comments" %>
    </div>

</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <div class='u-card'>
        <div class='u-img'>
            <%= image_tag 'image-placeholder.png', width:'150px', height:'150px' %>
        </div>
        <div class ='u-name-counter-col'>
            <%= link_to user_path(user.id) do %>
                <h1 class='user-name'><%= user.name %></h1>
            <% end %>
            <p class='u-posts-counter'>Number of posts: <%=  user.posts_counter  %></p>     
        </div>    
    </div>   
<%end%>

app/views/users/show.html.erb
<div class='u-detail-body'>
    <div class='u-detail-top'>
        <div class='u-d-img'>
            <%= image_tag 'image-placeholder.png', width: '150px', height: '150px' %>
        </div>

        <div class='u-detail-user'>
            <h1 class='u-detail-user-name'>
                <%= @user.name  %>
            </h1>
            <p class='u-detail-user-counter'>
                Number of posts: <%= @user.posts_counter %>
            </p>
        </div>
    </div>

    <div class='u-detail-bio'>
        <h2>Bio</h2>
        <p>
            <%= @user.bio %>
        </p>
    </div>

    <div class='u-detail-rec-posts'>
        <% @user.recent_posts.each  do |post| %>
            <div class='u-detail-rec-posts-card'>
                <h2>
                    Post: <%= post.title  %>
                </h2>
                <p>
                    <%= post.text %>
                </p>

                <div class='com-lik-counters'>
                    <p>Comments: <%= post.comments_counter %></p>
                    <p>Likes: <%= post.likes_counter %></p>
                </div>
            </div>
        <% end %>

        <button class='all-posts-btn'>
            <%= link_to 'See all posts', user_posts_path(@user), {:class => 'button_class'} %>
        </button>
    </div>
</div>